import fs from 'node:fs';

/**
 * @url https://developer.chrome.com/docs/extensions/reference/api/i18n#support_multiple_languages
 */
const SUPPORTED_LANGUAGES = {
  ar: 'Arabic',
  am: 'Amharic',
  bg: 'Bulgarian',
  bn: 'Bengali',
  ca: 'Catalan',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  en_AU: 'English (Australia)',
  en_GB: 'English (Great Britain)',
  en_US: 'English (USA)',
  es: 'Spanish',
  es_419: 'Spanish (Latin America and Caribbean)',
  et: 'Estonian',
  fa: 'Persian',
  fi: 'Finnish',
  fil: 'Filipino',
  fr: 'French',
  gu: 'Gujarati',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  kn: 'Kannada',
  ko: 'Korean',
  lt: 'Lithuanian',
  lv: 'Latvian',
  ml: 'Malayalam',
  mr: 'Marathi',
  ms: 'Malay',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt_BR: 'Portuguese (Brazil)',
  pt_PT: 'Portuguese (Portugal)',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sl: 'Slovenian',
  sr: 'Serbian',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  vi: 'Vietnamese',
  zh_CN: 'Chinese (China)',
  zh_TW: 'Chinese (Taiwan)',
};

import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const locales = fs.readdirSync(path.join(__dirname, 'locales'));

locales.forEach(locale => {
  if (!(locale in SUPPORTED_LANGUAGES)) {
    throw new Error(`Unsupported language: ${locale}`);
  }
});

makeTypeFile(locales);
makeGetMessageFromLocaleFile(locales);

function makeTypeFile(locales) {
  const typeFile = `/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
${locales.map(locale => `import type ${locale}Message from '../locales/${locale}/messages.json';`).join('\n')}

export type MessageKey = ${locales.map(locale => `keyof typeof ${locale}Message`).join(' & ')};

export type DevLocale = ${locales.map(locale => `'${locale}'`).join(' | ')};
`;

  fs.writeFileSync(path.join(__dirname, 'lib/type.ts'), typeFile);
}

function makeGetMessageFromLocaleFile(locales) {
  const supportedLocalesCode = JSON.stringify(locales).replace(/"/g, "'").replace(/,/g, ', ');

  const getMessageFromLocaleFile = `/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
${locales.map(locale => `import ${locale}Message from '../locales/${locale}/messages.json';`).join('\n')}

export const supportedLocales = ${supportedLocalesCode} as const;
export type SupportedLocale = (typeof supportedLocales)[number];

function isSupportedLocale(value: string): value is SupportedLocale {
  return (supportedLocales as readonly string[]).includes(value);
}

export function getMessageFromLocale(locale: string) {
  switch (locale) {
${locales
  .map(
    locale => `    case '${locale}':
      return ${locale}Message;`,
  )
  .join('\n')}
    default:
      throw new Error('Unsupported locale');
  }
}

/**
 * Resolves user language setting to a concrete locale.
 * - \`auto\` follows browser language with sane fallbacks.
 * - explicit locales are accepted when supported.
 */
export function resolveLocale(language: string | undefined | null): SupportedLocale {
  if (language && language !== 'auto') {
    const normalizedLanguage = language.replace('-', '_');
    if (isSupportedLocale(normalizedLanguage)) {
      return normalizedLanguage;
    }
  }

  const browserLocale = Intl.DateTimeFormat().resolvedOptions().locale.replace('-', '_');
  if (isSupportedLocale(browserLocale)) {
    return browserLocale;
  }

  const browserLang = browserLocale.split('_')[0];
  const localeByLanguageCode = supportedLocales.find(locale => locale.split('_')[0] === browserLang);
  if (localeByLanguageCode) {
    return localeByLanguageCode;
  }

  return supportedLocales[0];
}

export const defaultLocale = resolveLocale('auto');
`;
  fs.writeFileSync(path.join(__dirname, 'lib/getMessageFromLocale.ts'), getMessageFromLocaleFile);
}
